apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: 309179335397.dkr.ecr.us-east-1.amazonaws.com/demos:latest
        ports:
        - name: tomcat-port
          containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 80
    targetPort: tomcat-port
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer
